// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBFUmmDjJykQufv9g-rt23GvBLALq_w6vY",
      authDomain: "e-commerce-5eec4.firebaseapp.com",
      projectId: "e-commerce-5eec4",
      storageBucket: "e-commerce-5eec4.appspot.com",
      messagingSenderId: "440769775394",
      appId: "1:440769775394:web:0868650eb462ac8d02477b");
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0J6L6r2lHaq6L3VXEhlDuxYLHHjvevBs',
    appId: '1:440769775394:android:1dd6883af1910f4702477b',
    messagingSenderId: '440769775394',
    projectId: 'e-commerce-5eec4',
    storageBucket: 'e-commerce-5eec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dmxBNldQC8a7tZRblXexwHtkxFYbQ60',
    appId: '1:440769775394:ios:50caa67da1ffe7ef02477b',
    messagingSenderId: '440769775394',
    projectId: 'e-commerce-5eec4',
    storageBucket: 'e-commerce-5eec4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
